name: Clippie
options:
  bundleIdPrefix: com.clippie
  deploymentTarget:
    macOS: "13.0"
  xcodeVersion: "15.0"
  createIntermediateGroups: true
  defaultConfig: Release

settings:
  base:
    MACOSX_DEPLOYMENT_TARGET: "13.0"
    SWIFT_VERSION: "5.9"
    ARCHS: arm64
    VALID_ARCHS: arm64
    EXCLUDED_ARCHS[sdk=macosx*]: x86_64

packages:
  KeyboardShortcuts:
    url: https://github.com/sindresorhus/KeyboardShortcuts
    from: "2.0.0"
  GRDB:
    url: https://github.com/groue/GRDB.swift
    from: "7.0.0"

targets:
  Clippie:
    type: application
    platform: macOS
    sources:
      - path: Clippie
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.clippie.app
        PRODUCT_NAME: Clippie
        MARKETING_VERSION: "0.1.0"
        CURRENT_PROJECT_VERSION: "1"
        INFOPLIST_FILE: Clippie/Resources/Info.plist
        CODE_SIGN_ENTITLEMENTS: Clippie/Resources/Clippie.entitlements
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/../Frameworks"
        ENABLE_HARDENED_RUNTIME: true
        CODE_SIGN_IDENTITY: "-"
        GENERATE_INFOPLIST_FILE: false
    dependencies:
      - package: KeyboardShortcuts
      - package: GRDB
        product: GRDB
    entitlements:
      path: Clippie/Resources/Clippie.entitlements
  ClippieDev:
    type: application
    platform: macOS
    sources:
      - path: Clippie
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.clippie.app.dev
        PRODUCT_NAME: "Clippie Dev"
        MARKETING_VERSION: "0.1.0"
        CURRENT_PROJECT_VERSION: "1"
        INFOPLIST_FILE: Clippie/Resources/Info.plist
        CODE_SIGN_ENTITLEMENTS: Clippie/Resources/Clippie.entitlements
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/../Frameworks"
        ENABLE_HARDENED_RUNTIME: true
        CODE_SIGN_IDENTITY: "-"
        GENERATE_INFOPLIST_FILE: false
    dependencies:
      - package: KeyboardShortcuts
      - package: GRDB
        product: GRDB
    entitlements:
      path: Clippie/Resources/Clippie.entitlements
